### ISSUE TITLE
Extended partition has type 0x0f

### ISSUE THREAD

**Issue by jviotti** [jhermsmeier/node-mbr#3]
I have an image file (*.img) which I know the fourth partition is an extended partition (I can read it's first 512 bytes with node-mbr to reveal the logical partitions successfully), however the partition has a type of `0x0f`, where `partition-types.js` says that it should be `0x05` instead: https://github.com/jhermsmeier/node-mbr/blob/master/lib/partition-types.js#L12.

Is there a better way to check if a partition is an extended partition?

**Comment by jhermsmeier** [comment]
Thanks for bringing this up – that's interesting. I'll do some more research into partition types – I very much suspected that the information in this repository is far from complete. Can you share the MBR of that image file?

> Is there a better way to check if a partition is an extended partition?

Attempting to read & parse the first sector of each partition as an EBR (see [README](https://github.com/jhermsmeier/node-mbr#handling-logical-partitions) should give you the ability to determine if that partition is an extendended partition. Other than this, I can't think of another way to do this more reliably off the top of my head. I'll also look into that & extend the README.

**Comment by jviotti** [comment]
@jhermsmeier Uploaded the MBR here: http://filebin.ca/1yPxpxEqC2rI/rpi.data.

**Comment by jhermsmeier** [comment]
Great, thanks! I also discovered a more reliable source of information regarding MBR partition types, will add & update in a few hours. `0x0F` is indeed an `MS_EXTENDED` type.

**Comment by jviotti** [comment]
@jhermsmeier Sounds good! I'd be nice to also have a function `isExtendedPartitionType()` that takes a type and compares it to all recognised extended partition types.

**Comment by jhermsmeier** [comment]
@jviotti Good idea, will implement!

**Comment by jhermsmeier** [comment]
@jviotti Currently rethinking the API a bit – do you have any feedback regarding the current one? Something else you'd like to see?

**Comment by jviotti** [comment]
@jhermsmeier I don't like the current object-oriented like approach that requires me to instantiate MBR with the buffer to get access to the data.

I'd like a more functional approach instead:

```coffee
mbr = require('mbar')
myMbr = mbr.parse(myBuffer)
console.log(myMbr.partitions)
```

Also, it might be nice to have some utilities functions to perform common tasks. For example to read the MBR directly from a device or a *img file:

```coffee
mbr.read '/dev/disk2', (error, myMBR) ->
mbr.read 'path/to/image.img', (error, myMBR) ->
```

I understand that this module may explicitly want to avoid dealing with I/O and focusing on making sense of the actual buffer, so maybe other utilities might fit, like `mbr.isExtendedPartition()`, `mbr.isLogicalPartition()`, etc.

**Comment by jviotti** [comment]
My current use case is that I need to get the offset of a certain partition.

A function that I tend to use is:

```coffee
getPartitionOffset = (partition) ->
    return partition.firstLBA * 512
```

**Comment by jhermsmeier** [comment]
First of all, thanks a lot for all the input! Really appreciate it!

> I'd like a more functional approach instead:

You can actually do that – see [lib/mbr.js#L33](https://github.com/jhermsmeier/node-mbr/blob/master/lib/mbr.js#L33) – it just isn't documented very well. I'll think more about catering for both object oriented and functional approaches – depending on where & how I use it I'd also like the option to choose between the two.

> My current use case is that I need to get the offset of a certain partition

The thing is, that some blockdevices don't have a block size of 512 bytes, and thus I'd like to keep calculations involving block sizes out of this module – but on the other hand, the block size could be supplied to the function as an optional argument. I'll keep it in mind!

> I understand that this module may explicitly want to avoid dealing with I/O

Yes, exactly. The I/O is supposed to be dealt with in [node-disk](https://github.com/jhermsmeier/node-disk), which I sadly haven't gotten around to implementing to a publishable state, because I ran into issues with [node-blockdevice](https://github.com/jhermsmeier/node-blockdevice). Guess I should spend some time on that again as well :)

> maybe other utilities might fit, like `mbr.isExtendedPartition()`, `mbr.isLogicalPartition()`, etc.

Yeah, those are a really good idea! They'd be methods on a `partition` though (or "static" methods on the constructor taking a `partition` as an argument).

**Comment by jviotti** [comment]
@jhermsmeier You're welcome, looking forward to such improvements!

I noticed you have quite some low-level nodejs utilities. I wonder if they are part of a bigger project?

**Comment by jhermsmeier** [comment]
@jviotti So I started munching trough the code, current development is on [node-mbr/tree/next](https://github.com/jhermsmeier/node-mbr/tree/next) – in case you want to check that out (you'll have to read the code though, docs will be updated later; and that's still a WIP).

> I noticed you have quite some low-level nodejs utilities. I wonder if they are part of a bigger project?

Yes, mainly [node-disk](https://github.com/jhermsmeier/node-disk) – which was supposed to tie a whole bunch of things together (like [node-ntfs](https://github.com/jhermsmeier/node-ntfs), [node-fat32](https://github.com/jhermsmeier/node-fat32), [node-vhd](https://github.com/jhermsmeier/node-vhd) and a few others) – sadly not really getting around to that though (dayjob etc.)

**Comment by jviotti** [comment]
@jhermsmeier Great, I'll have a look soon.

**Comment by jhermsmeier** [comment]
@jviotti Sorry it took this long – but `0.4.0` is out now. Docs in the README still aren't very helpful, but I'll work on that (the comments in the code should help for now though).

**Comment by jviotti** [comment]
@jhermsmeier Looks great, thanks a lot. I'll be working with it during the next few days and I'll let you know if I stumble into any other issue.

**Comment by jhermsmeier** [comment]
@jviotti Excellent. Yes, please do! Guess I can close this now? (Feel free to reopen, and we can also keep the discussion going here)

Also, may I ask what you're using this for? Curious!

**Comment by jviotti** [comment]
@jhermsmeier Sounds fine, good to close.

I'm working at a CLI tool for https://resin.io. The configuration injection to the downloaded operating system images is assisted by `node-mbr`. You can take a closer look at https://github.com/resin-io/resin-config-inject.

Thanks for developing such useful modules!

**Comment by jhermsmeier** [comment]
> Thanks for developing such useful modules!

Very appreciated – glad it's useful!

>  I'm working at a CLI tool for https://resin.io.

That looks interesting. I've had a look at resin.io and signed up – sadly I don't have a functioning Raspberry at the moment, to fiddle around with things, but will probably order some new ones soon.

PS: I took up development on [node-disk](https://github.com/jhermsmeier/node-disk) again – that might be interesting for you as well. It's pretty hacky at the moment, but improvements are coming soon. Would appreciate feedback on that as well, if you're interested.

**Comment by jviotti** [comment]
@jhermsmeier Looks good. I'll play around with it in the future!
